name: msc
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13.*
  - ipykernel
  - ipywidgets
  - tqdm
  - fenics-dolfinx=0.9.0
  - mpich=4.3.2
  - pyvista=0.46.3
  - matplotlib=3.10.8
  - numpy=2.4.0
  - trame=3.12.0
  - open3d=0.19.0
  - scikit-image=0.25.2
  - adios4dolfinx=0.9.5
  - pip 
  - pip:
      - gmsh==4.14.1
      - -e .[dev]

